# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "Cherry Kiwi"

# URL
url: "https://cherry-kiwi.github.io"
baseurl: ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name: "About"
    href: "/about"

  - name: "GitHub"
    href: "https://github.com/cherry-kiwi/cherry-kiwi.github.io"
# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
